apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: validator-api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: dev1-dataworkbench-io
spec:
  backend:
    serviceName: validator-api
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: validator-api
  labels:
    app: validator-api
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: api-server
  selector:
    app: validator-api
    tier: frontend
