apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validator-api
  labels:
    app: validator-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: validator-api
        tier: frontend
    spec:
      containers:
      - name: validator-api-app
        image: gcr.io/dataworkbench-io/validator-api
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - name: api-server
          containerPort: 8080
        env:
          - name: PROJECT_ID
            value: dataworkbench-io
