
# Site settings
title: Validator API
email: rolf@drostan.org
description: >
  Validator API engine
brand: DataWorkbench
github: https://github.com/data4development/IATI-data-validator-api

defaults:
  -
    values:
      layout: "default"

remote_theme: data4development/dataworkbench-jekyll-theme
